sonar.projectKey=anneso09_skillhub-ec09
sonar.organization=anneso09-1

sonar.sources=skillhub-backend/app
sonar.tests=skillhub-backend/tests
sonar.exclusions=**/vendor/**,**/node_modules/**,**/target/**,**/.github/**,skillhub-auth/**

sonar.php.coverage.reportPaths=skillhub-backend/coverage.xml