sonar.projectKey=anneso09_skillhub-ec06
sonar.organization=anneso09-1

sonar.sources=skillhub-backend/app

sonar.exclusions=**/vendor/**,**/node_modules/**,**/target/**,**/tests/**,**/.github/**,skillhub-auth/**